### PR TITLE
show books details

### PR DESCRIPTION
**Pull request by HuyLuuVan**
+ Show Books Details Complete
+ https://edu-redmine.sun-asterisk.vn/issues/26118

### CODE REVIEW

**Comment by BuBuHuy** [comment]
Ready

Show Books Details Complete
https://edu-redmine.sun-asterisk.vn/issues/26118

**Comment by dhhIntern** [comment]
Rebase về 1 commit kìa Huy

**Comment by HuyLuuVan** [comment]
> Rebase về 1 commit kìa Huy

Dạ vâng

**Comment by dhhIntern** [comment]
> > Rebase về 1 commit kìa Huy
> 
> Dạ vâng

Dạ vâng luôn =))

**Comment by vanvtt-0952** [comment]
commented
bjk lun, bjk thfi đừng ready nhé

**Pull request closed without merging**
